# Google Mail configuration
camel.component.google-mail-stream.clientId=<YOUR_CLIENT_ID>
camel.component.google-mail-stream.clientSecret=<YOUR_CLIENT_SECRET>
camel.component.google-mail-stream.refreshToken=<YOUR_REFRESH_TOKEN>
camel.component.google-mail.clientId=<YOUR_CLIENT_ID>
camel.component.google-mail.clientSecret=<YOUR_CLIENT_SECRET>
camel.component.google-mail.refreshToken=<YOUR_REFRESH_TOKEN>